local health = require("mark.health")
local mark = require("mark")

describe("Health Check", function()
  describe("Default configuration", function()
    before_each(function()
      mark.setup({})
    end)

    it("runs health check without errors", function()
      assert.has_no_errors(function()
        health.check()
      end)
    end)
  end)

  describe("Custom configuration", function()
    before_each(function()
      mark.setup({ skills_dir = "/tmp/mark-health-test" })
    end)

    it("runs health check with custom options", function()
      assert.has_no_errors(function()
        health.check()
      end)
    end)
  end)
end)
