local mark = require("mark")

describe("mark.nvim", function()
  describe("Default setup", function()
    before_each(function()
      mark.setup({})
    end)

    it("can list skills", function()
      local skills = mark.list_skills()
      assert.is_true(#skills > 0)
    end)

    it("has builtin skills", function()
      local skill = mark.get_skill("code-review")
      assert.is_not_nil(skill)
      assert.are.equal("Code Review", skill.display_name)
      assert.are.equal("review", skill.category)
    end)

    it("can install a skill", function()
      local ok = mark.install("code-review")
      assert.is_true(ok)
      local skill = mark.get_skill("code-review")
      assert.is_true(skill.installed)
    end)

    it("can uninstall a skill", function()
      mark.install("code-review")
      local ok = mark.uninstall("code-review")
      assert.is_true(ok)
      local skill = mark.get_skill("code-review")
      assert.is_false(skill.installed)
    end)

    it("returns false for unknown skills", function()
      local ok = mark.install("nonexistent-skill")
      assert.is_false(ok)
    end)

    it("can get installed skills", function()
      mark.install("code-review")
      mark.install("test-generation")
      local installed = mark.get_installed()
      assert.is_true(#installed >= 2)
    end)

    it("can get combined system prompt", function()
      mark.install("code-review")
      local prompt = mark.get_system_prompt()
      assert.is_true(#prompt > 0)
      assert.is_truthy(prompt:find("Code Review"))
    end)
  end)

  describe("Custom setup", function()
    it("accepts custom skills_dir", function()
      mark.setup({ skills_dir = "/tmp/mark-test-skills" })
      local config = require("mark.config").options
      assert.are.equal("/tmp/mark-test-skills", config.skills_dir)
    end)

    it("accepts custom ui options", function()
      mark.setup({ ui = { border = "double" } })
      local config = require("mark.config").options
      assert.are.equal("double", config.ui.border)
    end)
  end)
end)
